name: Ruby CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Ruby tests and linter
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10 # this might cause issues if there are more than 10 commits in a PR (?)
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Tests
        run: bundle exec rake
      - name: RuboCop
        run: bin/rubocop
